# SemCor Noun-Only Demo

This notebook focuses on noun annotations only.

In [1]:
from itertools import islice
from pathlib import Path

import pandas as pd

from prepare_semcor import (
    get_sentence_record_by_index,
    iter_noun_annotation_records,
    iter_noun_sentence_records,
    load_semcor_stats,
)

BASE_DIR = Path("data/semcor")

In [2]:
stats = load_semcor_stats(BASE_DIR)
pd.Series(stats)

dataset_name                                                             SemCor
base_dir                                   /home/xiaoyue/LiteSemRAG/data/semcor
nltk_data_dir                 /home/xiaoyue/LiteSemRAG/data/semcor/raw/nltk_...
processed_dir                    /home/xiaoyue/LiteSemRAG/data/semcor/processed
resources                                            [semcor, wordnet, omw-1.4]
file_count                                                                  352
sentence_count                                                            37176
token_count                                                              820410
annotation_count                                                         778587
semantic_annotation_count                                                235079
noun_annotation_count                                                     88892
oov_entity_count                                                           9684
multiword_annotation_count                                                34261
sentence_jsonl                /home/xiaoyue/LiteSemRAG/data/semcor/processed...
annotation_jsonl              /home/xiaoyue/LiteSemRAG/data/semcor/processed...
noun_sentence_jsonl           /home/xiaoyue/LiteSemRAG/data/semcor/processed...
noun_annotation_jsonl         /home/xiaoyue/LiteSemRAG/data/semcor/processed...
dtype: object

In [3]:
noun_sentence_sample = next(iter(iter_noun_sentence_records(BASE_DIR, limit=1)))
print(noun_sentence_sample["sentence_id"])
print(noun_sentence_sample["text"])

pd.DataFrame(noun_sentence_sample["noun_annotations"])[
    [
        "annotation_index",
        "text",
        "tokens",
        "lemma",
        "pos",
        "sense_key",
        "synset_name",
        "synset_definition",
    ]
]

brown1/tagfiles/br-a01.xml:1
The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced ``no evidence'' that any irregularities took place.

,annotation_index,text,tokens,lemma,pos,sense_key,synset_name,synset_definition
0,1,Fulton_County_Grand_Jury,"[Fulton, County, Grand, Jury]",group,NNP,group%1:03:00::,group.n.01,any number of entities (members) considered as...
1,3,Friday,[Friday],friday,NN,friday%1:28:00::,friday.n.01,the sixth day of the week; the fifth working day
2,5,investigation,[investigation],investigation,NN,investigation%1:09:00::,probe.n.01,an inquiry into unfamiliar or questionable act...
3,7,Atlanta,[Atlanta],atlanta,NN,atlanta%1:15:00::,atlanta.n.01,state capital and largest city of Georgia; chi...
4,10,primary_election,"[primary, election]",primary_election,NN,primary_election%1:04:00::,primary.n.01,a preliminary election where delegates or nomi...
5,14,evidence,[evidence],evidence,NN,evidence%1:09:00::,evidence.n.01,your basis for belief or disbelief; knowledge ...
6,18,irregularities,[irregularities],irregularity,NN,irregularity%1:04:00::,abnormality.n.04,behavior that breaches the rule or etiquette o...

In [7]:
def inspect_sentence_by_index(sentence_index: int) -> pd.DataFrame:
    sentence = get_sentence_record_by_index(sentence_index, BASE_DIR)
    noun_annotations = sentence["noun_annotations"]

    print(f"sentence_index: {sentence_index}")
    print(f"sentence_id: {sentence['sentence_id']}")
    print("sentence_text:")
    print(sentence["text"])
    print()
    print("noun surface tokens:")
    print([annotation["tokens"] for annotation in noun_annotations])

    return pd.DataFrame(noun_annotations)[
        [
            "annotation_index",
            "text",
            "tokens",
            "lemma",
            "pos",
            "sense_key",
            "synset_name",
            "synset_definition",
        ]
    ]


inspect_sentence_by_index(0)

sentence_index: 0
sentence_id: brown1/tagfiles/br-a01.xml:1
sentence_text:
The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced ``no evidence'' that any irregularities took place.

noun surface tokens:
[['Fulton', 'County', 'Grand', 'Jury'], ['Friday'], ['investigation'], ['Atlanta'], ['primary', 'election'], ['evidence'], ['irregularities']]

,annotation_index,text,tokens,lemma,pos,sense_key,synset_name,synset_definition
0,1,Fulton_County_Grand_Jury,"[Fulton, County, Grand, Jury]",group,NNP,group%1:03:00::,group.n.01,any number of entities (members) considered as...
1,3,Friday,[Friday],friday,NN,friday%1:28:00::,friday.n.01,the sixth day of the week; the fifth working day
2,5,investigation,[investigation],investigation,NN,investigation%1:09:00::,probe.n.01,an inquiry into unfamiliar or questionable act...
3,7,Atlanta,[Atlanta],atlanta,NN,atlanta%1:15:00::,atlanta.n.01,state capital and largest city of Georgia; chi...
4,10,primary_election,"[primary, election]",primary_election,NN,primary_election%1:04:00::,primary.n.01,a preliminary election where delegates or nomi...
5,14,evidence,[evidence],evidence,NN,evidence%1:09:00::,evidence.n.01,your basis for belief or disbelief; knowledge ...
6,18,irregularities,[irregularities],irregularity,NN,irregularity%1:04:00::,abnormality.n.04,behavior that breaches the rule or etiquette o...

In [5]:
noun_preview = list(islice(iter_noun_annotation_records(BASE_DIR), 20))
pd.DataFrame(noun_preview)[
    [
        "sentence_id",
        "text",
        "tokens",
        "lemma",
        "pos",
        "sense_key",
        "synset_name",
    ]
]

,sentence_id,text,tokens,lemma,pos,sense_key,synset_name
0,brown1/tagfiles/br-a01.xml:1,Fulton_County_Grand_Jury,"[Fulton, County, Grand, Jury]",group,NNP,group%1:03:00::,group.n.01
1,brown1/tagfiles/br-a01.xml:1,Friday,[Friday],friday,NN,friday%1:28:00::,friday.n.01
2,brown1/tagfiles/br-a01.xml:1,investigation,[investigation],investigation,NN,investigation%1:09:00::,probe.n.01
3,brown1/tagfiles/br-a01.xml:1,Atlanta,[Atlanta],atlanta,NN,atlanta%1:15:00::,atlanta.n.01
4,brown1/tagfiles/br-a01.xml:1,primary_election,"[primary, election]",primary_election,NN,primary_election%1:04:00::,primary.n.01
5,brown1/tagfiles/br-a01.xml:1,evidence,[evidence],evidence,NN,evidence%1:09:00::,evidence.n.01
6,brown1/tagfiles/br-a01.xml:1,irregularities,[irregularities],irregularity,NN,irregularity%1:04:00::,abnormality.n.04
7,brown1/tagfiles/br-a01.xml:2,jury,[jury],jury,NN,jury%1:14:00::,jury.n.01
8,brown1/tagfiles/br-a01.xml:2,term,[term],term,NN,term%1:28:00::,term.n.02
9,brown1/tagfiles/br-a01.xml:2,end,[end],end,NN,end%1:28:00::,end.n.02
10,brown1/tagfiles/br-a01.xml:2,presentments,[presentments],presentment,NN,presentment%1:04:00::,presentment.n.01
11,brown1/tagfiles/br-a01.xml:2,City_Executive_Committee,"[City, Executive, Committee]",group,NNP,group%1:03:00::,group.n.01
12,brown1/tagfiles/br-a01.xml:2,charge,[charge],charge,NN,charge%1:04:03::,mission.n.03
13,brown1/tagfiles/br-a01.xml:2,election,[election],election,NN,election%1:04:01::,election.n.01
14,brown1/tagfiles/br-a01.xml:2,praise,[praise],praise,NN,praise%1:10:00::,praise.n.01
15,brown1/tagfiles/br-a01.xml:2,thanks,[thanks],thanks,NN,thanks%1:10:00::,thanks.n.01
16,brown1/tagfiles/br-a01.xml:2,City_of_Atlanta,"[City, of, Atlanta]",location,NNP,location%1:03:00::,location.n.01
17,brown1/tagfiles/br-a01.xml:2,manner,[manner],manner,NN,manner%1:07:02::,manner.n.01
18,brown1/tagfiles/br-a01.xml:2,election,[election],election,NN,election%1:04:01::,election.n.01
19,brown1/tagfiles/br-a01.xml:3,September,[September],september,NN,september%1:28:00::,september.n.01

In [6]:
def find_nouns_by_lemma(target_lemma: str, limit: int = 10) -> pd.DataFrame:
    rows = []
    for record in iter_noun_annotation_records(BASE_DIR):
        if record.get("lemma") == target_lemma:
            rows.append(
                {
                    "sentence_id": record["sentence_id"],
                    "text": record["text"],
                    "tokens": record["tokens"],
                    "lemma": record["lemma"],
                    "synset_name": record["synset_name"],
                    "definition": record["synset_definition"],
                }
            )
        if len(rows) >= limit:
            break
    return pd.DataFrame(rows)


find_nouns_by_lemma("evidence", limit=10)

,sentence_id,text,tokens,lemma,synset_name,definition
0,brown1/tagfiles/br-a01.xml:1,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
1,brown1/tagfiles/br-b20.xml:39,evidence,[evidence],evidence,evidence.n.02,an indication that makes something evident
2,brown1/tagfiles/br-d02.xml:9,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
3,brown1/tagfiles/br-d02.xml:10,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
4,brown1/tagfiles/br-d03.xml:62,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
5,brown1/tagfiles/br-f03.xml:22,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
6,brown1/tagfiles/br-f03.xml:54,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
7,brown1/tagfiles/br-f10.xml:32,evidence,[evidence],evidence,evidence.n.03,(law) all the means by which any alleged matte...
8,brown1/tagfiles/br-f10.xml:95,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...
9,brown1/tagfiles/br-f19.xml:84,evidence,[evidence],evidence,evidence.n.01,your basis for belief or disbelief; knowledge ...